/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./internal/templates/**/*.html",
    "./internal/handlers/**/*.go",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#001a41",
        "on-primary-fixed-variant": "#004493",
        "outline": "#727785",
        "on-background": "#191c1f",
        "surface-container": "#eceef2",
        "outline-variant": "#c1c6d6",
        "tertiary-container": "#c55500",
        "on-tertiary-fixed": "#341100",
        "surface-variant": "#e1e2e6",
        "error-container": "#ffdad6",
        "primary-fixed": "#d8e2ff",
        "background": "#f8f9fd",
        "secondary": "#475e8c",
        "on-secondary-fixed-variant": "#2e4673",
        "on-primary-fixed": "#001a41",
        "surface-tint": "#005bc0",
        "tertiary-fixed-dim": "#ffb691",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#414754",
        "surface-container-low": "#f2f4f8",
        "on-tertiary-fixed-variant": "#783100",
        "surface-container-highest": "#e1e2e6",
        "on-primary-container": "#ffffff",
        "primary": "#005bbf",
        "primary-container": "#1a73e8",
        "on-secondary-container": "#3d5481",
        "tertiary": "#9e4300",
        "on-error-container": "#93000a",
        "surface-container-high": "#e6e8ec",
        "inverse-surface": "#2d3134",
        "inverse-on-surface": "#eff1f5",
        "secondary-fixed": "#d8e2ff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#adc7ff",
        "surface-dim": "#d8dade",
        "inverse-primary": "#adc7ff",
        "secondary-fixed-dim": "#afc7fb",
        "on-tertiary-container": "#0e0200",
        "secondary-container": "#b2c9fe",
        "surface-bright": "#f8f9fd",
        "on-error": "#ffffff",
        "on-surface": "#191c1f",
        "on-tertiary": "#ffffff",
        "surface": "#f8f9fd",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdbcb",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.75rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
